stages:
  - build
  - deploy

build_frontend_production:
  image: node:12
  stage: build
  before_script:
    - yarn
  script: yarn build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules
  artifacts:
    paths:
      - build
  only:
    refs:
     - master

build_frontend_staging:
  image: node:12
  stage: build
  before_script:
    - yarn
  script:
    - export REACT_APP_BASEURL=$STAGING_BASEURL # set REACT_APP variables before build command
    - export REACT_APP_CUSTOMER_BASEURL=$STAGING_CUSTOMER_BASEURL # set REACT_APP variables before build command
    - yarn build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules
  artifacts:
    paths:
      - build
  only:
    refs:
     - staging

deploy_production:
  image: google/cloud-sdk:alpine
  stage: deploy
  environment: Production
  only:
  - master
  script:
  - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
  - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  - gcloud --quiet --project $PROJECT_ID app deploy app.yaml
  after_script:
  - rm /tmp/$CI_PIPELINE_ID.json

deploy_staging:
  image: google/cloud-sdk:alpine
  stage: deploy
  environment: Staging
  only:
  - staging
  script:
  - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
  - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  - gcloud --quiet --project $PROJECT_ID app deploy app-staging.yaml
  after_script:
  - rm /tmp/$CI_PIPELINE_ID.json
